name: Build Windows EXE

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Semak Keluar Kod
      uses: actions/checkout@v4

    - name: Sediakan Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Pasang Library Required
      run: |
        python -m pip install --upgrade pip
        pip install customtkinter pyinstaller pillow

    - name: Bina Fail .exe
      run: |
        pyinstaller --noconsole --onefile --add-data "soalan.json;." main.py

    - name: Muat Naik Hasil .exe
      uses: actions/upload-artifact@v4
      with:
        name: Aplikasi-Belajar-Windows
        path: dist/*.exe
